### ISSUE TITLE
Inconsistent data formats

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/device-aggregator#16]
During SSI test run http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/4088/ on the reactive architecture patch stack (https://github.com/intel-hpdd/intel-manager-for-lustre/pull/467) when creating filesystem, failure occurs because disk[12,14] missing a single `VolumeNode`  each (only 6 in db where 8 are expected). 

```
chroma=> select * from chroma_core_volumenode where not_deleted=true;
 id | volume_id | host_id |                          path                          | storage_resource_id | primary | use | not_deleted
----+-----------+---------+--------------------------------------------------------+---------------------+---------+-----+-------------
  1 |         4 |       1 | /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14        |                  13 | f       | f   | t
 23 |         4 |       2 | /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14        |                  78 | f       | f   | t
  2 |         5 |       1 | /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12        |                  18 | f       | f   | t
 24 |         5 |       2 | /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12        |                  83 | f       | f   | t
...
 34 |         4 |       4 | /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14        |                 107 | f       | t   | t
 13 |         5 |       3 | /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12        |                  59 | f       | t   | t
```

The reason for the missing  nodes could be due to exceptions when processing the `device-aggregator` output in turn caused by differences in formatting of the host data.

```
[2018-03-05 23:16:23,401: ERROR/agent_daemon] Exception in agent session for linux from lotus-45vm17.lotus.hpdd.lab.intel.com: 
Traceback (most recent call last): 
  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py", line 168, in on_message
    session.plugin.do_agent_session_start(message['body'])
  File "/usr/share/chroma-manager/chroma_core/lib/storage_plugin/base_plugin.py", line 122, in do_agent_session_start
    self._initial_populate(self.agent_session_start, self._root_resource.host_id, data)
  File "/usr/share/chroma-manager/chroma_core/lib/storage_plugin/base_plugin.py", line 187, in _initial_populate
    fn(*args)
  File "/usr/share/chroma-manager/chroma_core/plugins/linux.py", line 200, in agent_session_start
    devices = get_block_devices(fqdn)
  File "/usr/share/chroma-manager/chroma_core/plugins/block_devices.py", line 531, in get_block_devices
    device_maps, _data = get_host_devices(fqdn, _data)
TypeError: 'NoneType' object is not iterable
```

The data processed for the given host seems to be the `blockDevices` value rather than the whole dict structure with top-level keys `blockDevices` and `zed`.

```
[2018-03-05 23:16:23,400: DEBUG/plugin_runner] fetching devices for lotus-45vm17.lotus.hpdd.lab.intel.com
[2018-03-05 23:16:23,401: ERROR/plugin_runner] badly formatted data found for lotus-45vm17.lotus.hpdd.lab.intel.com : {u'/devices/pci0000:00/0000:00:05.0/virtio1/host2/target2:0:0/2:0:0:12/block/sdc/sdc1': {u'IML_DM_SLAVE_MMS': [], u'ID_PART_ENTRY_NUMBER': 1, u'IML_SIZE': u'20951040', 
...
```

We can verify that this data is being presented by the `device-aggregator` in such a way by looking at it's output directly:

```
...
lotus-45vm16.lotus.hpdd.lab.intel.com

{u'/devices/pci0000:00/0000:00:05.0/virtio1/host2/target2:0:0/2:0:0:12/block/sdc/sdc1': {u'IML_DM_SLAVE_MMS': [], u'ID_PART_ENTRY_NUMBER': 1, u'IML_SIZE': u'20951040', u'IML_MD_DEVICES': [], u'DM_UUID': None, u'ID_VENDOR': u'QEMU', u'ID_SERIAL': 
...

lotus-45vm17.lotus.hpdd.lab.intel.com

{u'blockDevices': {u'/devices/pci0000:00/0000:00:05.0/virtio1/host2/target2:0:0/2:0:0:12/block/sdc/sdc1': {u'IML_DM_SLAVE_MMS': [], u'ID_PART_ENTRY_NUMBER': 1, u'IML_SIZE': u'20951040', u'IML_MD_DEVICES': [], u'DM_UUID': None, u'ID_VENDOR': u'QEMU', u'ID_SERIAL': 
...
```

This does not seem to be directly related to the `device-scanner` output  as `Info` commands issued on the relevant hosts yield consistent data.

The possibility of mixed scanner/proxy versions on different hosts has also been ruled out.

Reinstalling device-scanner doesn't seem to resolve the issue.

**Comment by tanabarr** [comment]
one theory is that at some stage the device-scanner emits an intermediate state of a different format, possibly during start-up which is cached by the device aggregator and causes these formatting errors

**Comment by jgrund** [comment]
> The data processed for the given host seems to be the blockDevices value rather than the whole dict structure with top-level keys blockDevices and zed.

This sounds like a backcompat issue. I wonder if we are sending the V1 request anwhere in this stack.

**Comment by tanabarr** [comment]
The problem source seem to be  that the old format of `device-scanner` output was being triggered using the old-style info command (`{"ACTION": "info"}) which was being propagated through to the `device-aggregator` and causing exceptions in the manager `plugin_runner` process. 

These calls were being triggered when dead code was being activated through importing a module with a class whose `__init__` function send the relevant command to the socket.

What is not explained yet is why this only occurred on a single storage server and not all of them.

The offending files are removed in commit https://github.com/intel-hpdd/intel-manager-for-lustre/pull/467/commits/470950466a56f291d9a5a0fdf660fa3fec0ee979

**Comment by jgrund** [comment]
And the device-scanner side is being solved in: 

https://github.com/intel-hpdd/device-scanner/issues/101
